package com.mycompany.Poke151;

import java.util.HashMap;
import android.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import android.content.res.Resources;
import android.widget.SearchView.*;
import android.content.*;

public class MainActivity extends Activity
{
	
	private static final String MATCH_HIRAGANA = "[\\u3040-\\u309F]+$";
	private static final String MATCH_KATAKANA  = "[\\u30A0-\\u30FF]+$";
	
	HashMap<String, String> name_map = new HashMap<String, String>();
	
    /** Called when the activity is first created. */
    @Override
    public void onCreate(Bundle savedInstanceState)
	{
        super.onCreate(savedInstanceState);
        setContentView(R.layout.table);
		
		Button btn = (Button)findViewById(R.id.button);
		btn.setOnClickListener(new OnClickListener(){
			
			public void onClick(View v){
			//get text
			EditText text_box = (EditText)findViewById(R.id.text_box);
			
			String inp_text = text_box.getText().toString();
			
				if (inp_text.matches(MATCH_HIRAGANA)){
				Utils ul = new Utils();
				inp_text = ul.KanaHenkan(inp_text);
				Toast toast_1 = Toast.makeText(MainActivity.this, inp_text, Toast.LENGTH_LONG);
				toast_1.show();
				
				}else if (!inp_text.matches(MATCH_HIRAGANA) && !inp_text.matches(MATCH_KATAKANA)){
				Toast toast = Toast.makeText(MainActivity.this, "カタカナ、又はひらがなで入力してください。", Toast.LENGTH_LONG);
				toast.show();
			}
			
			if(inp_text.equals(getString(R.string.POKE001))){
				findViewById(R.id.POKE001).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME001).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE002))){
				findViewById(R.id.POKE002).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME002).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE003))){
				findViewById(R.id.POKE003).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME003).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE004))){
				findViewById(R.id.POKE004).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME004).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE005))){
				findViewById(R.id.POKE005).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME005).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE006))){
				findViewById(R.id.POKE006).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME006).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE007))){
				findViewById(R.id.POKE007).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME007).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE008))){
				findViewById(R.id.POKE008).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME008).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE009))){
				findViewById(R.id.POKE009).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME009).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE010))){
				findViewById(R.id.POKE010).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME010).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE011))){
				findViewById(R.id.POKE011).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME011).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE012))){
				findViewById(R.id.POKE012).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME012).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE013))){
				findViewById(R.id.POKE013).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME013).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE014))){
				findViewById(R.id.POKE014).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME014).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE015))){
				findViewById(R.id.POKE015).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME015).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE016))){
				findViewById(R.id.POKE016).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME016).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE017))){
				findViewById(R.id.POKE017).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME017).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE018))){
				findViewById(R.id.POKE018).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME018).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE019))){
				findViewById(R.id.POKE019).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME019).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE020))){
				findViewById(R.id.POKE020).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME020).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE021))){
				findViewById(R.id.POKE021).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME021).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE022))){
				findViewById(R.id.POKE022).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME022).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE023))){
				findViewById(R.id.POKE023).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME023).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE024))){
				findViewById(R.id.POKE024).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME024).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE025))){
				findViewById(R.id.POKE025).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME025).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE026))){
				findViewById(R.id.POKE026).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME026).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE027))){
				findViewById(R.id.POKE027).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME027).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE028))){
				findViewById(R.id.POKE028).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME028).setVisibility(View.VISIBLE);
			}	
				if(inp_text.equals(getString(R.string.POKE029)) || inp_text.equals("ニドランメス")){
				findViewById(R.id.POKE029).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME029).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE030))){
				findViewById(R.id.POKE030).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME030).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE031))){
				findViewById(R.id.POKE031).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME031).setVisibility(View.VISIBLE);
			}	
				if(inp_text.equals(getString(R.string.POKE032)) || inp_text.equals("ニドランオス")){
				findViewById(R.id.POKE032).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME032).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE033))){
				findViewById(R.id.POKE033).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME033).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE034))){
				findViewById(R.id.POKE034).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME034).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE035))){
				findViewById(R.id.POKE035).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME035).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE036))){
				findViewById(R.id.POKE036).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME036).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE037))){
				findViewById(R.id.POKE037).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME037).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE038))){
				findViewById(R.id.POKE038).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME038).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE039))){
				findViewById(R.id.POKE039).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME039).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE040))){
				findViewById(R.id.POKE040).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME040).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE041))){
				findViewById(R.id.POKE041).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME041).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE042))){
				findViewById(R.id.POKE042).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME042).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE043))){
				findViewById(R.id.POKE043).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME043).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE044))){
				findViewById(R.id.POKE044).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME044).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE045))){
				findViewById(R.id.POKE045).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME045).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE046))){
				findViewById(R.id.POKE046).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME046).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE047))){
				findViewById(R.id.POKE047).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME047).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE048))){
				findViewById(R.id.POKE048).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME048).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE049))){
				findViewById(R.id.POKE049).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME049).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE050))){
				findViewById(R.id.POKE050).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME050).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE051))){
				findViewById(R.id.POKE051).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME051).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE052))){
				findViewById(R.id.POKE052).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME052).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE053))){
				findViewById(R.id.POKE053).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME053).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE054))){
				findViewById(R.id.POKE054).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME054).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE055))){
				findViewById(R.id.POKE055).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME055).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE056))){
				findViewById(R.id.POKE056).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME056).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE057))){
				findViewById(R.id.POKE057).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME057).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE058))){
				findViewById(R.id.POKE058).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME058).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE059))){
				findViewById(R.id.POKE059).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME059).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE060))){
				findViewById(R.id.POKE060).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME060).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE061))){
				findViewById(R.id.POKE061).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME061).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE062))){
				findViewById(R.id.POKE062).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME062).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE063))){
				findViewById(R.id.POKE063).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME063).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE064))){
				findViewById(R.id.POKE064).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME064).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE065))){
				findViewById(R.id.POKE065).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME065).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE066))){
				findViewById(R.id.POKE066).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME066).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE067))){
				findViewById(R.id.POKE067).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME067).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE068))){
				findViewById(R.id.POKE068).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME068).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE069))){
				findViewById(R.id.POKE069).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME069).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE070))){
				findViewById(R.id.POKE070).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME070).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE071))){
				findViewById(R.id.POKE071).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME071).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE072))){
				findViewById(R.id.POKE072).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME072).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE073))){
				findViewById(R.id.POKE073).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME073).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE074))){
				findViewById(R.id.POKE074).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME074).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE075))){
				findViewById(R.id.POKE075).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME075).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE076))){
				findViewById(R.id.POKE076).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME076).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE077))){
				findViewById(R.id.POKE077).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME077).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE078))){
				findViewById(R.id.POKE078).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME078).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE079))){
				findViewById(R.id.POKE079).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME079).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE080))){
				findViewById(R.id.POKE080).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME080).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE081))){
				findViewById(R.id.POKE081).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME081).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE082))){
				findViewById(R.id.POKE082).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME082).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE083))){
				findViewById(R.id.POKE083).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME083).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE084))){
				findViewById(R.id.POKE084).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME084).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE085))){
				findViewById(R.id.POKE085).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME085).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE086))){
				findViewById(R.id.POKE086).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME086).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE087))){
				findViewById(R.id.POKE087).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME087).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE088))){
				findViewById(R.id.POKE088).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME088).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE089))){
				findViewById(R.id.POKE089).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME089).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE090))){
				findViewById(R.id.POKE090).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME090).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE091))){
				findViewById(R.id.POKE091).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME091).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE092))){
				findViewById(R.id.POKE092).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME092).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE093))){
				findViewById(R.id.POKE093).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME093).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE094))){
				findViewById(R.id.POKE094).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME094).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE095))){
				findViewById(R.id.POKE095).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME095).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE096))){
				findViewById(R.id.POKE096).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME096).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE097))){
				findViewById(R.id.POKE097).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME097).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE098))){
				findViewById(R.id.POKE098).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME098).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE099))){
				findViewById(R.id.POKE099).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME099).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE100))){
				findViewById(R.id.POKE100).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME100).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE101))){
				findViewById(R.id.POKE101).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME101).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE102))){
				findViewById(R.id.POKE102).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME102).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE103))){
				findViewById(R.id.POKE103).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME103).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE104))){
				findViewById(R.id.POKE104).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME104).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE105))){
				findViewById(R.id.POKE105).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME105).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE106))){
				findViewById(R.id.POKE106).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME106).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE107))){
				findViewById(R.id.POKE107).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME107).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE108))){
				findViewById(R.id.POKE108).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME108).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE109))){
				findViewById(R.id.POKE109).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME109).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE110))){
				findViewById(R.id.POKE110).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME110).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE111))){
				findViewById(R.id.POKE111).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME111).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE112))){
				findViewById(R.id.POKE112).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME112).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE113))){
				findViewById(R.id.POKE113).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME113).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE114))){
				findViewById(R.id.POKE114).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME114).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE115))){
				findViewById(R.id.POKE115).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME115).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE116))){
				findViewById(R.id.POKE116).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME116).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE117))){
				findViewById(R.id.POKE117).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME117).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE118))){
				findViewById(R.id.POKE118).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME118).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE119))){
				findViewById(R.id.POKE119).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME119).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE120))){
				findViewById(R.id.POKE120).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME120).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE121))){
				findViewById(R.id.POKE121).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME121).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE122))){
				findViewById(R.id.POKE122).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME122).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE123))){
				findViewById(R.id.POKE123).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME123).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE124))){
				findViewById(R.id.POKE124).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME124).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE125))){
				findViewById(R.id.POKE125).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME125).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE126))){
				findViewById(R.id.POKE126).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME126).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE127))){
				findViewById(R.id.POKE127).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME127).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE128))){
				findViewById(R.id.POKE128).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME128).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE129))){
				findViewById(R.id.POKE129).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME129).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE130))){
				findViewById(R.id.POKE130).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME130).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE131))){
				findViewById(R.id.POKE131).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME131).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE132))){
				findViewById(R.id.POKE132).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME132).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE133))){
				findViewById(R.id.POKE133).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME133).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE134))){
				findViewById(R.id.POKE134).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME134).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE135))){
				findViewById(R.id.POKE135).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME135).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE136))){
				findViewById(R.id.POKE136).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME136).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE137))){
				findViewById(R.id.POKE137).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME137).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE138))){
				findViewById(R.id.POKE138).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME138).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE139))){
				findViewById(R.id.POKE139).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME139).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE140))){
				findViewById(R.id.POKE140).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME140).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE141))){
				findViewById(R.id.POKE141).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME141).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE142))){
				findViewById(R.id.POKE142).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME142).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE143))){
				findViewById(R.id.POKE143).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME143).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE144))){
				findViewById(R.id.POKE144).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME144).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE145))){
				findViewById(R.id.POKE145).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME145).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE146))){
				findViewById(R.id.POKE146).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME146).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE147))){
				findViewById(R.id.POKE147).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME147).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE148))){
				findViewById(R.id.POKE148).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME148).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE149))){
				findViewById(R.id.POKE149).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME149).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE150))){
				findViewById(R.id.POKE150).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME150).setVisibility(View.VISIBLE);
			}	
			if(inp_text.equals(getString(R.string.POKE151))){
				findViewById(R.id.POKE151).setVisibility(View.VISIBLE);
				findViewById(R.id.NAME151).setVisibility(View.VISIBLE);
			}
			
			text_box.setText("");
			
			}
		});
    }
		

}
